workflows:
  android-debug:
    name: Build Android Debug APK
    environment:
      java: 17
      sdk: "33"
    scripts:
      - chmod +x gradlew
      - ./gradlew assembleDebug
    artifacts:
      - app/build/outputs/apk/debug/*.apk
    cache:
      - ~/.gradle/caches
      - ~/.m2/repository
      - ~/.konan